/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\public\assets\3d\dna_rna_animated_visualization.glb 
Author: Nortenko Dmytro (https://sketchfab.com/leondp)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/dna-rna-animated-visualization-f0ef115f9e9646a28642a2d509b8d727
Title: DNA, RNA animated visualization
*/
import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { Group } from 'three'
import { useFrame } from '@react-three/fiber'

export function Dna_rna_animated_visualization() {
  const { scene, animations } = useGLTF('/assets/3d/dna_rna_animated_visualization.glb')
  const group = useRef<Group>(null)
  const { actions } = useAnimations(animations, group)
  const firstAction = actions[Object.keys(actions)[0]]; // Try the first animation
  useFrame(() => {
    if (actions) {
      if (firstAction) firstAction.play();
    }
  });
  return (
    <primitive ref={group} object={scene} scale={1.5} position={[0, 0, 0]} />
  )
}

useGLTF.preload('/assets/3d/dna_rna_animated_visualization.glb')
