/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\public\assets\3d\dna_smoother_mesh.glb 
Author: KageG (https://sketchfab.com/KageG)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/dna-smoother-mesh-16372395afcf4cb9a9209f77e865caac
Title: DNA Smoother Mesh
*/
"use client"
import { useGLTF, useAnimations } from '@react-three/drei'
import { useFrame } from '@react-three/fiber';
import { useRef } from 'react';
import { Group } from 'three';


export function Dna_smoother_mesh() {
  const group = useRef<Group>(null)
  const { scene, animations } = useGLTF('/assets/3d/dna_smoother_mesh.glb')
  const { actions } = useAnimations(animations, group);
  const firstAction = actions[Object.keys(actions)[0]]; // Try the first animation
  useFrame(() => {
    if (actions) {
      if (firstAction) firstAction.setDuration(7.5).play()
    }
  });
  return (
    <primitive ref={group} object={scene} scale={1.5} position={[0, 0, 0]} />
  )
}

useGLTF.preload('/assets/3d/dna_smoother_mesh.glb')
