/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\public\assets\3d\island.glb 
*/
"use client"
import { useAnimations, useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber';

export default function Island(props) {
  const { nodes, materials, animations, scene } = useGLTF('/assets/3d/island.glb');
  const { actions } = useAnimations(animations, scene);
  const firstAction = actions[Object.keys(actions)[0]]; // Try the first animation
  useFrame(() => {
    if (actions) {
      if (firstAction) firstAction.play();
    }
  });
  return (
    <group scale={.1} {...props} dispose={null}>
      <mesh geometry={nodes.pCube11_rocks1_0.geometry} material={materials.PaletteMaterial001} />
      <mesh geometry={nodes.Cube.geometry} material={materials.Material} />
      <mesh geometry={nodes.polySurface944_tree_body_0.geometry} material={materials.PaletteMaterial001} position={[5.89, 0, -3.945]} rotation={[0, -0.901, 0]} />
      <mesh geometry={nodes.polySurface944_tree_body_0001.geometry} material={materials.PaletteMaterial001} position={[1.552, -0.792, 32.888]} rotation={[-Math.PI, 0.528, -Math.PI]} scale={0.581} />
      <mesh geometry={nodes.polySurface944_tree_body_0002.geometry} material={materials.PaletteMaterial001} position={[20.57, -1.167, 22.781]} rotation={[Math.PI, -0.346, Math.PI]} />
      <mesh geometry={nodes.polySurface944_tree_body_0003.geometry} material={materials.PaletteMaterial001} position={[-17.263, -0.809, 18.121]} rotation={[0, 0.36, 0]} />
      <mesh geometry={nodes.polySurface944_tree_body_0004.geometry} material={materials.PaletteMaterial001} position={[30.764, -0.776, 27.677]} rotation={[Math.PI, -0.374, Math.PI]} />
      <mesh geometry={nodes.polySurface944_tree_body_0005.geometry} material={materials.PaletteMaterial001} position={[17.488, -0.563, 19.436]} rotation={[Math.PI, -0.346, Math.PI]} scale={0.73} />
      <mesh geometry={nodes.polySurface944_tree_body_0006.geometry} material={materials.PaletteMaterial001} position={[14.66, -0.457, 17.591]} rotation={[Math.PI, -0.961, Math.PI]} scale={0.73} />
      <mesh geometry={nodes.polySurface944_tree_body_0007.geometry} material={materials.PaletteMaterial001} position={[4.221, -0.276, 18.706]} rotation={[Math.PI, -1.233, Math.PI]} scale={0.477} />
      <mesh geometry={nodes.polySurface945_tree1_0.geometry} material={materials.PaletteMaterial001} position={[5.89, 0, -3.945]} rotation={[0, -0.901, 0]} />
      <mesh geometry={nodes.polySurface945_tree1_0001.geometry} material={materials.PaletteMaterial001} position={[1.552, -0.792, 32.888]} rotation={[-Math.PI, 0.528, -Math.PI]} scale={0.581} />
      <mesh geometry={nodes.polySurface945_tree1_0002.geometry} material={materials.PaletteMaterial001} position={[20.57, -1.167, 22.781]} rotation={[Math.PI, -0.346, Math.PI]} />
      <mesh geometry={nodes.polySurface945_tree1_0003.geometry} material={materials.PaletteMaterial001} position={[-17.263, -0.809, 18.121]} rotation={[0, 0.36, 0]} />
      <mesh geometry={nodes.polySurface945_tree1_0004.geometry} material={materials.PaletteMaterial001} position={[17.488, -0.563, 19.436]} rotation={[Math.PI, -0.346, Math.PI]} scale={0.73} />
      <mesh geometry={nodes.polySurface946_tree2_0.geometry} material={materials.PaletteMaterial001} position={[5.89, 0, -3.945]} rotation={[0, -0.901, 0]} />
      <mesh geometry={nodes.polySurface946_tree2_0001.geometry} material={materials.PaletteMaterial001} position={[1.552, -0.792, 32.888]} rotation={[-Math.PI, 0.528, -Math.PI]} scale={0.581} />
      <mesh geometry={nodes.polySurface946_tree2_0002.geometry} material={materials.PaletteMaterial001} position={[20.57, -1.167, 22.781]} rotation={[Math.PI, -0.346, Math.PI]} />
      <mesh geometry={nodes.polySurface946_tree2_0003.geometry} material={materials.PaletteMaterial001} position={[-17.263, -0.809, 18.121]} rotation={[0, 0.36, 0]} />
      <mesh geometry={nodes.polySurface946_tree2_0004.geometry} material={materials.PaletteMaterial001} position={[30.764, -0.776, 27.677]} rotation={[Math.PI, -0.374, Math.PI]} />
      <mesh geometry={nodes.polySurface947_tree1_0.geometry} material={materials.PaletteMaterial001} position={[5.89, 0, -3.945]} rotation={[0, -0.901, 0]} />
      <mesh geometry={nodes.polySurface947_tree1_0001.geometry} material={materials.PaletteMaterial001} position={[20.57, -1.167, 22.781]} rotation={[Math.PI, -0.346, Math.PI]} />
      <mesh geometry={nodes.polySurface947_tree1_0002.geometry} material={materials.PaletteMaterial001} position={[-17.263, -0.809, 18.121]} rotation={[0, 0.36, 0]} />
      <mesh geometry={nodes.polySurface947_tree1_0003.geometry} material={materials.PaletteMaterial001} position={[30.764, -0.776, 27.677]} rotation={[Math.PI, -0.374, Math.PI]} />
      <mesh geometry={nodes.polySurface947_tree1_0004.geometry} material={materials.PaletteMaterial001} position={[4.221, -0.276, 18.706]} rotation={[Math.PI, -1.233, Math.PI]} scale={0.477} />
      <mesh geometry={nodes.polySurface948_tree_body_0.geometry} material={materials.PaletteMaterial001} position={[5.89, 0, -3.945]} rotation={[0, -0.901, 0]} />
      <mesh geometry={nodes.polySurface948_tree_body_0001.geometry} material={materials.PaletteMaterial001} position={[1.552, -0.792, 32.888]} rotation={[-Math.PI, 0.528, -Math.PI]} scale={0.581} />
      <mesh geometry={nodes.polySurface948_tree_body_0002.geometry} material={materials.PaletteMaterial001} position={[20.57, -1.167, 22.781]} rotation={[Math.PI, -0.346, Math.PI]} />
      <mesh geometry={nodes.polySurface948_tree_body_0003.geometry} material={materials.PaletteMaterial001} position={[-17.263, -0.809, 18.121]} rotation={[0, 0.36, 0]} />
      <mesh geometry={nodes.polySurface948_tree_body_0004.geometry} material={materials.PaletteMaterial001} position={[30.764, -0.776, 27.677]} rotation={[Math.PI, -0.374, Math.PI]} />
      <mesh geometry={nodes.polySurface948_tree_body_0005.geometry} material={materials.PaletteMaterial001} position={[17.488, -0.563, 19.436]} rotation={[Math.PI, -0.346, Math.PI]} scale={0.73} />
      <mesh geometry={nodes.polySurface948_tree_body_0006.geometry} material={materials.PaletteMaterial001} position={[14.66, -0.457, 17.591]} rotation={[Math.PI, -0.961, Math.PI]} scale={0.73} />
      <mesh geometry={nodes.polySurface948_tree_body_0007.geometry} material={materials.PaletteMaterial001} position={[4.221, -0.276, 18.706]} rotation={[Math.PI, -1.233, Math.PI]} scale={0.477} />
      <mesh geometry={nodes.polySurface949_tree_body_0.geometry} material={materials.PaletteMaterial001} position={[5.89, 0, -3.945]} rotation={[0, -0.901, 0]} />
      <mesh geometry={nodes.polySurface949_tree_body_0001.geometry} material={materials.PaletteMaterial001} position={[1.552, -0.792, 32.888]} rotation={[-Math.PI, 0.528, -Math.PI]} scale={0.581} />
      <mesh geometry={nodes.polySurface949_tree_body_0002.geometry} material={materials.PaletteMaterial001} position={[20.57, -1.167, 22.781]} rotation={[Math.PI, -0.346, Math.PI]} />
      <mesh geometry={nodes.polySurface949_tree_body_0003.geometry} material={materials.PaletteMaterial001} position={[-17.263, -0.809, 18.121]} rotation={[0, 0.36, 0]} />
      <mesh geometry={nodes.polySurface949_tree_body_0004.geometry} material={materials.PaletteMaterial001} position={[30.764, -0.776, 27.677]} rotation={[Math.PI, -0.374, Math.PI]} />
      <mesh geometry={nodes.polySurface949_tree_body_0005.geometry} material={materials.PaletteMaterial001} position={[17.488, -0.563, 19.436]} rotation={[Math.PI, -0.346, Math.PI]} scale={0.73} />
      <mesh geometry={nodes.polySurface949_tree_body_0006.geometry} material={materials.PaletteMaterial001} position={[14.66, -0.457, 17.591]} rotation={[Math.PI, -0.961, Math.PI]} scale={0.73} />
      <mesh geometry={nodes.polySurface949_tree_body_0007.geometry} material={materials.PaletteMaterial001} position={[4.221, -0.276, 18.706]} rotation={[Math.PI, -1.233, Math.PI]} scale={0.477} />
    </group>
  )
}

useGLTF.preload('/assets/3d/island.glb')
