/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\public\assets\3d\sustainable_globe.glb 
Author: StartledLlama (https://sketchfab.com/StartledLlama)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/sustainable-globe-54998d9b1d3445b3b9969609353edf18
Title: Sustainable Globe
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { Group } from 'three';
import { useFrame } from '@react-three/fiber';


export function Sustainable_globe_model() {
  const group = useRef<Group|null>(null)
  const { scene, animations } = useGLTF('/assets/3d/sustainable_globe.glb')
  const { actions } = useAnimations(animations, group);
  const firstAction = actions[Object.keys(actions)[0]];
  useFrame(() => {
    if(firstAction){
      firstAction.play();
    }
  });
  return (
    <primitive ref={group} object={scene} scale={1.5} position={[0, 0, 0]} />
  )
}

useGLTF.preload('/assets/3d/sustainable_globe.glb')
